name: n_c_protocols
description: North Carolina Protocol Hub Flutter App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 48.0.1+1



environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  dio: ^5.3.3
  flutter_pdfview: ^1.3.1
  flutter_animate: ^4.1.1+1
  flutter_easyloading: ^3.0.5
  flutter_cache_manager: ^3.3.0
  font_awesome_flutter: ^10.8.0
  from_css_color: ^2.0.0
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  audioplayers: ^6.1.0
  intl: ^0.19.0
  json_path: ^0.7.4
  page_transition: ^2.0.4
  path_provider: ^2.0.14
  path_provider_android: ^2.0.25
  pdf: ^3.10.4
  plugin_platform_interface: ^2.1.3
  provider: ^6.0.4
  shared_preferences: ^2.3.3
  sqflite: ^2.2.6
  stream_transform: ^2.1.0
  timeago: ^3.2.2
  url_launcher: ^6.2.5
  progress_dialog_null_safe: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  google_mobile_ads: ^5.2.0
  flutter_email_sender: ^6.0.2
  purchases_flutter: ^8.2.1
  http: ^1.2.1
  will_it_run: ^1.0.4
  firebase_database: ^11.1.4
  cupertino_icons: ^1.0.0
  app_tracking_transparency: ^2.0.6



dev_dependencies:
  msix: ^3.16.8


  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/statelogo_white.png"
  adaptive_icon_foreground: "/images/statelogo_white.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/statelogo_white.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/statelogo_white.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/statelogo_white.png"

msix_config:
  display_name: Nc Protocol Hub
  publisher_display_name: Dean Apps
  publisher: CN=69FC1453-E56D-4253-B21C-A093772F57E5
  logo_path: C:\Users\Wills\Desktop\AppCodeGeneral\GitHub\n_c_protocols\assets\images\statelogo.png
  identity_name: 37417DeanApps.FoECompanion
  msix_version: 1.0.1.0
  store: true


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/icon/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/images/info/




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
