// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaXqubgz5bF_J3siUOPyPTgCiu9gDPkUE',
    appId: '1:860169251888:web:7374eaa009528db2f251f5',
    messagingSenderId: '860169251888',
    projectId: 'ncprotocols-661da',
    authDomain: 'ncprotocols-661da.firebaseapp.com',
    databaseURL: 'https://ncprotocols-661da-default-rtdb.firebaseio.com',
    storageBucket: 'ncprotocols-661da.appspot.com',
    measurementId: 'G-7H7W80P128',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP4YTDjV5Ngi0yGva5rFxg7JTfOhNRLYE',
    appId: '1:860169251888:android:66c5dca2dbde15f7f251f5',
    messagingSenderId: '860169251888',
    projectId: 'ncprotocols-661da',
    databaseURL: 'https://ncprotocols-661da-default-rtdb.firebaseio.com',
    storageBucket: 'ncprotocols-661da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL5rQOu1KoFBWwLuMzTefKn_sJqfg9LzQ',
    appId: '1:860169251888:ios:48da8037af793ee9f251f5',
    messagingSenderId: '860169251888',
    projectId: 'ncprotocols-661da',
    databaseURL: 'https://ncprotocols-661da-default-rtdb.firebaseio.com',
    storageBucket: 'ncprotocols-661da.appspot.com',
    iosBundleId: 'com.deanapps.ncstateprotocols',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL5rQOu1KoFBWwLuMzTefKn_sJqfg9LzQ',
    appId: '1:860169251888:ios:52b916cbf3fef6c0f251f5',
    messagingSenderId: '860169251888',
    projectId: 'ncprotocols-661da',
    databaseURL: 'https://ncprotocols-661da-default-rtdb.firebaseio.com',
    storageBucket: 'ncprotocols-661da.appspot.com',
    iosBundleId: 'com.deanapps.ncstateprotocols',
  );
}
